# Generated by Django 3.0.3 on 2020-02-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
